# Generated by Django 3.1.5 on 2021-01-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('header_data', models.TextField(default='{}')),
                ('form_data', models.TextField(default='{}')),
            ],
        ),
    ]
