# Generated by Django 3.1.5 on 2021-01-16 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formclip', '0003_auto_20210115_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formclip.userurlmap'),
            preserve_default=False,
        ),
    ]
